/* =====================================================================
   RICONCILIAZIONE FATTURA XML IT02448510046TESI3_VG3VQ.xml  -  gazza_tc
   SOLA LETTURA: solo SELECT / WITH. Nessuna scrittura, nessun #tmp, nessun EXEC.

   Esecuzione (dal PC che vede il server):
     sqlcmd -S gfbia25 -E -C -d gazza_tc -i query_eseguite_IT02448510046TESI3_VG3VQ.sql -o output.txt -s"|" -W

   Versione 2: nomi di colonne e chiavi VERIFICATI sul catalogo incollato dall'utente (passo 1).
   Differenze rispetto alla v1:
     - MUSTWEB_FILE.DATA_DOC e' varchar(20): le date si leggono da MUSTWEB_HEAD.DATA_DOC (datetime)
     - ORD_FOR_RIGHE: chiave riga = DOC_RIGA_ID (DDT_FOR_RIGHE_SPEC.ORD_RIGA_ID punta a questa)
     - FATT_FOR_SPEC non ha il fornitore: join con FATT_FOR.COD_CF
     - MUSTWEB_XML.ROW_DOC e' image: si usa DATALENGTH, non CAST a NVARCHAR
     - colonne text (DES_RIGA, NOTE_*) non selezionate con * ma castate o escluse
   ===================================================================== */

-- ===== PASSO 0: verifica connessione ==================================
SELECT DB_NAME() AS db, @@SERVERNAME AS server;
GO

-- ===== PASSO 1: catalogo (gia' eseguito dall'utente, output ricevuto) ==
-- vedi output catalogo; non ripetere.

-- ===== PASSO 2: controllo preliminare - file Mustweb e collegamenti ====
SELECT NOME_FILE, DOC_ID, COD_CF, P_IVA, COD_FISC, DENOMINAZIONE, TIPO_DOC, DATA_DOC, DATA_DOC_FILTRO,
       DATA_RICEZIONE, VIM_NUMBER, FORM_TRASM_XML, FLAG_STAMPATO, FLAG_CONTR, FLAG_ALLEGATI, FLAG_TIPO_OPE
FROM MUSTWEB_FILE
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO
SELECT DOC_ID, TABLE_ORIG, NOME_FILE, DATA_RICEZIONE, VIM_NUMBER
FROM MUSTWEB_DOC_LINK
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO
SELECT HEAD_CONT_ID, NOME_FILE, DATA_RICEZIONE, VIM_NUMBER
FROM MUSTWEB_LINK
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO

-- ===== PASSO 3: testata, righe, riepiloghi IVA (XML) ===================
SELECT FILE_ID, NOME_FILE, COD_CF, RAG_SOC_CF, TIPO_DOC, NUM_DOC_FOR, DATA_DOC, CAUSALE, TOTALE_DOC_V1,
       CASSA_PREV, CASSA_IMPORTO, TIPO_RITENUTA, IMPORTO_RIT, ALIQUOTA_RIT, CAUSALE_RIT, DATA_RIC, SPESA_BOLLO_V1
FROM MUSTWEB_HEAD
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO
SELECT NUM_RIGA, TIPO_RIGA, COD_ART, COD_ART_XML_1, COD_ART_XML_2, COD_ART_XML_3, COD_ART_XML_4, COD_ART_XML_5,
       DES_RIGA, QUANT_RIGA, UM, PREZZO_LORDO_VU1,
       SCONTO_1, SCONTO_2, SCONTO_3, SCONTO_4, SCONTO_5, IMPORTO_V1, PERC_IVA, COD_IVA, COD_TIPO_NAT,
       FLAG_OMAGGIO, COD_CONTO
FROM MUSTWEB_RIGHE
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'
ORDER BY NUM_RIGA;
GO
SELECT PROGR_TOT, COD_IVA, PERC_IVA, IMPONIBILE_V1, IVA_V1, ESIGIBILITA, RIFERIMENTO, ARRO, COD_TIPO_NAT
FROM MUSTWEB_TOT
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'
ORDER BY PROGR_TOT;
GO
-- Quadratura righe XML
SELECT COUNT(*) AS n_righe, SUM(IMPORTO_V1) AS somma_righe, SUM(QUANT_RIGA) AS somma_quant
FROM MUSTWEB_RIGHE
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO
SELECT SUM(IMPONIBILE_V1) AS somma_imponibili, SUM(IVA_V1) AS somma_iva, SUM(ARRO) AS somma_arro
FROM MUSTWEB_TOT
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO

-- ===== PASSO 4: duplicati fattura (stesso fornitore e stesso numero) ===
SELECT f.DOC_ID, f.COD_CF, f.DATA_DOC, s.NUM_FATT_FOR, s.DATA_FATT_FOR, s.TOTALE_FATT_FOR_V1,
       s.TOTALE_IVA_FATT_FOR_V1, s.FLAG_REGISTRATA, s.COD_RIF_CONT
FROM FATT_FOR_SPEC s
JOIN FATT_FOR f ON f.DOC_ID = s.DOC_ID
WHERE f.COD_CF = (SELECT TOP 1 COD_CF FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
  AND LTRIM(RTRIM(s.NUM_FATT_FOR)) = (SELECT TOP 1 LTRIM(RTRIM(NUM_DOC_FOR)) FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml');
GO

-- ===== PASSO 5: fornitore (confronto con CF) ===========================
SELECT f.COD_CF, f.P_IVA, f.COD_FISC, f.DENOMINAZIONE,
       c.RAG_SOC_CF, c.P_IVA_CF, c.COD_FISC_CF, c.STATO_CF, c.ISO_CF, c.E_MAIL_CF, c.FLAG_FOR
FROM MUSTWEB_FILE f
LEFT JOIN CF c ON c.COD_CF = f.COD_CF
WHERE f.NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO
-- Anagrafiche con la stessa P.IVA (per rilevare duplicati o COD_CF diverso)
SELECT c.COD_CF, c.RAG_SOC_CF, c.P_IVA_CF, c.COD_FISC_CF, c.STATO_CF, c.ISO_CF, c.FLAG_FOR
FROM CF c
WHERE c.P_IVA_CF IN (SELECT P_IVA FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
   OR c.P_IVA_CF IN (SELECT 'IT' + P_IVA FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml');
GO

-- ===== PASSO 6: verifica codici articolo proposti in ART_ANA ===========
SELECT r.NUM_RIGA, r.COD_ART AS cod_mustweb, r.DES_RIGA AS des_xml,
       r.COD_ART_XML_1, r.COD_ART_XML_2, r.COD_ART_XML_3,
       a.DES_ART AS des_art_ana, a.COD_CAT, a.UM_BASE, a.COD_CF AS cod_cf_art, a.COD_TAGLIA, a.FLAG_INATTIVO, a.FLAG_OBSOLETO
FROM MUSTWEB_RIGHE r
LEFT JOIN ART_ANA a ON a.COD_ART = r.COD_ART
WHERE r.NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'
ORDER BY r.NUM_RIGA;
GO

-- ===== PASSO 7: DDT candidati non fatturati dello stesso fornitore =====
-- Intervallo: data fattura -/+ 90 giorni (modificabile). Include totali DDT.
SELECT s.DOC_ID, s.NUM_DDT_FOR, s.DATA_DDT_FOR, d.DATA_DOC AS data_caricamento, d.COD_CF,
       s.FLAG_FATTURATO, s.FATTURA_ID, s.ORDINE_ID,
       t.TOT_MERCE_V1, t.TOT_SPESE_V1, t.IMPONIBILE_V1, t.IVA_V1, t.TOTALE_V1
FROM DDT_FOR_SPEC s
JOIN DDT_FOR d ON d.DOC_ID = s.DOC_ID
LEFT JOIN DDT_FOR_TOT t ON t.DOC_ID = s.DOC_ID
WHERE s.FLAG_FATTURATO = 0
  AND d.COD_CF = (SELECT TOP 1 COD_CF FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
  AND s.DATA_DDT_FOR BETWEEN
        DATEADD(DAY, -90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
    AND DATEADD(DAY,  90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
ORDER BY s.DATA_DDT_FOR, s.DOC_ID;
GO

-- ===== PASSO 7b: stesso fornitore, DDT GIA' fatturati nello stesso intervallo
-- (serve a motivare le esclusioni "gia' fatturato")
SELECT s.DOC_ID, s.NUM_DDT_FOR, s.DATA_DDT_FOR, s.FLAG_FATTURATO, s.FATTURA_ID
FROM DDT_FOR_SPEC s
JOIN DDT_FOR d ON d.DOC_ID = s.DOC_ID
WHERE s.FLAG_FATTURATO <> 0
  AND d.COD_CF = (SELECT TOP 1 COD_CF FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
  AND s.DATA_DDT_FOR BETWEEN
        DATEADD(DAY, -90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
    AND DATEADD(DAY,  90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
ORDER BY s.DATA_DDT_FOR, s.DOC_ID;
GO

-- ===== PASSO 8: righe dei DDT candidati + legame ordine + articolo =====
SELECT r.DOC_ID, r.NUM_RIGA, r.DOC_RIGA_ID, r.COD_ART, a.DES_ART AS des_art_ana,
       CAST(r.DES_RIGA AS VARCHAR(300)) AS des_riga, r.COD_VAR, r.COD_ART_VAR,
       r.QUANT_RIGA, r.UM, r.PREZZO_NETTO_VU1, r.IMPORTO_V1,
       rs.ORD_RIGA_ID, rs.COD_ART_FOR, rs.UM_FORN, rs.FLAG_FATTURATO, rs.FATTURA_ID
FROM DDT_FOR_RIGHE r
LEFT JOIN DDT_FOR_RIGHE_SPEC rs ON rs.DOC_RIGA_ID = r.DOC_RIGA_ID
LEFT JOIN ART_ANA a ON a.COD_ART = r.COD_ART
WHERE r.DOC_ID IN (
  SELECT s.DOC_ID
  FROM DDT_FOR_SPEC s
  JOIN DDT_FOR d ON d.DOC_ID = s.DOC_ID
  WHERE s.FLAG_FATTURATO = 0
    AND d.COD_CF = (SELECT TOP 1 COD_CF FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
    AND s.DATA_DDT_FOR BETWEEN
          DATEADD(DAY, -90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
      AND DATEADD(DAY,  90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')))
ORDER BY r.DOC_ID, r.NUM_RIGA;
GO

-- ===== PASSO 9: righe ordine collegate (fornitore, articolo, q.ta', UM, prezzo)
-- ORD_FOR_RIGHE.DOC_RIGA_ID = DDT_FOR_RIGHE_SPEC.ORD_RIGA_ID
SELECT o.DOC_ID AS ord_doc_id, o.DOC_RIGA_ID AS ord_riga_id, o.NUM_RIGA, o.COD_CF, o.DATA_DOC,
       o.COD_ART, o.COD_VAR, o.COD_ART_VAR, CAST(o.DES_RIGA AS VARCHAR(300)) AS des_riga,
       o.QUANT_RIGA, o.UM, o.PREZZO_NETTO_VU1, o.IMPORTO_V1,
       os.COD_ART_FOR, os.UM_FORN, os.QUANT_CONS_RIGA, os.QUANT_DA_CONS_RIGA, os.FLAG_FATTURATO
FROM ORD_FOR_RIGHE o
LEFT JOIN ORD_FOR_RIGHE_SPEC os ON os.DOC_RIGA_ID = o.DOC_RIGA_ID
WHERE o.DOC_RIGA_ID IN (
  SELECT rs.ORD_RIGA_ID
  FROM DDT_FOR_RIGHE_SPEC rs
  WHERE rs.DOC_ID IN (
    SELECT s.DOC_ID
    FROM DDT_FOR_SPEC s
    JOIN DDT_FOR d ON d.DOC_ID = s.DOC_ID
    WHERE s.FLAG_FATTURATO = 0
      AND d.COD_CF = (SELECT TOP 1 COD_CF FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
      AND s.DATA_DDT_FOR BETWEEN
            DATEADD(DAY, -90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
        AND DATEADD(DAY,  90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))))
ORDER BY o.DOC_ID, o.NUM_RIGA;
GO

-- ===== PASSO 9b: testate degli ordini collegati ========================
SELECT od.DOC_ID, od.ANNO_DOC, od.SERIE_DOC, od.NUM_DOC, od.DATA_DOC, od.COD_CF,
       osp.NUM_ORDINE_FORNITORE, osp.DATA_ORDINE_FORNITORE, osp.FLAG_EVASO, osp.DATA_CONSEGNA
FROM ORD_FOR od
LEFT JOIN ORD_FOR_SPEC osp ON osp.DOC_ID = od.DOC_ID
WHERE od.DOC_ID IN (
  SELECT o.DOC_ID
  FROM ORD_FOR_RIGHE o
  WHERE o.DOC_RIGA_ID IN (
    SELECT rs.ORD_RIGA_ID
    FROM DDT_FOR_RIGHE_SPEC rs
    WHERE rs.DOC_ID IN (
      SELECT s.DOC_ID
      FROM DDT_FOR_SPEC s
      JOIN DDT_FOR d ON d.DOC_ID = s.DOC_ID
      WHERE s.FLAG_FATTURATO = 0
        AND d.COD_CF = (SELECT TOP 1 COD_CF FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
        AND s.DATA_DDT_FOR BETWEEN
              DATEADD(DAY, -90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
          AND DATEADD(DAY,  90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')))))
ORDER BY od.DATA_DOC, od.DOC_ID;
GO

-- ===== PASSO 10: spese dei DDT candidati ===============================
SELECT sp.DOC_ID, sp.DOC_SPESE_ID, sp.COD_TIPO_SPESA, sp.DES_TIPO_SPESA, sp.COD_SPESA, sp.DES_SPESA,
       sp.IMPORTO_SPESA_V1, sp.COD_IVA, sp.COD_CONTO
FROM DDT_FOR_SPESE sp
WHERE sp.DOC_ID IN (
  SELECT s.DOC_ID
  FROM DDT_FOR_SPEC s
  JOIN DDT_FOR d ON d.DOC_ID = s.DOC_ID
  WHERE s.FLAG_FATTURATO = 0
    AND d.COD_CF = (SELECT TOP 1 COD_CF FROM MUSTWEB_FILE WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')
    AND s.DATA_DDT_FOR BETWEEN
          DATEADD(DAY, -90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml'))
      AND DATEADD(DAY,  90, (SELECT TOP 1 DATA_DOC FROM MUSTWEB_HEAD WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml')))
ORDER BY sp.DOC_ID, sp.DOC_SPESE_ID;
GO

-- ===== PASSO 11 (solo se i dati estratti non bastano): XML originale ===
-- Solo dimensione; il frammento da leggere lo si decide dopo. ROW_DOC e' image.
SELECT NOME_FILE, DATALENGTH(ROW_DOC) AS byte_xml
FROM MUSTWEB_XML
WHERE NOME_FILE = 'IT02448510046TESI3_VG3VQ.xml';
GO
